sonar.projectKey=Projet-S3
<<<<<<< HEAD
sonar.host.url=http://localhost:9000
sonar.login=sqp_198e4c1995ee4aba8e0b1daf13b37a25b6db38db
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
=======
sonar.projectName=Projet S3 - Employee Management
sonar.projectVersion=1.0-SNAPSHOT
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.login=sqp_198e4c1995ee4aba8e0b1daf13b37a25b6db38db
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/target/**,**/*.xml
>>>>>>> 329955f44c7fe2b9d498008a5cc63bf10183481e
