# Informations du projet
sonar.projectKey=Projet-S3
sonar.projectName=Projet S3 - Employee Management
sonar.projectVersion=1.0

# Chemins des sources et des tests
sonar.sources=src/main/java
sonar.tests=src/test/java

# Encoding
sonar.sourceEncoding=UTF-8

# Langage
sonar.language=java

# Chemins des binaires compilés
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Librairies
sonar.java.libraries=target/**/*.jar

# Couverture de code avec JaCoCo
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclure certains fichiers
sonar.exclusions=**/target/**,**/node_modules/**,**/*.xml,**/*.yml,**/*.yaml

# Tests
sonar.test.inclusions=**/*Test.java,**/*Tests.java
