sonar.projectKey=Projet-S3
sonar.host.url=http://localhost:9000
sonar.login=sqp_198e4c1995ee4aba8e0b1daf13b37a25b6db38db
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8